import type { AppProps } from 'next/app';
import Head from 'next/head';
import 'antd/dist/antd.css';

import '../styles/globals.scss';
import { Header } from '../layouts/Header/Header';
import { Footer } from '../layouts/Footer/Footer';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Avito</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Component {...pageProps} />;
      <Footer />
    </>
  );
}

export default MyApp;
