import type { AppProps } from 'next/app';
import Head from 'next/head';

import '../styles/globals.scss';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Avito</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />;
    </>
  );
}

export default MyApp;
